### ISSUE TITLE
[Feature] 멘토 세부 설정 뷰 구현

### ISSUE THREAD

**Issue by sunnny619** [Soongsil-CoffeeChat/COGO-DEV-app#16]
## 목적

> 맨토 회원가입 이후 자기소개 설정 권유 다이얼로그 띄우기

## 작업 상세 내용

- [ ] 자기소개 설정 다이얼로그 만들기
- [ ] 다이얼로그 띄우는 조건 설정(회원가입 -> 멘토인데 자기소개 설정 안했을 시(홈 화면 진입시는 항상 띄우기) -> 다른 멘토 카드 눌렀을 시/코고 네비 눌렀을 시)

## 예상 소요시간

하루

**Comment by DevDAN09** [comment]
- [ ] 홈화면 진입시 바로 코고 멘토 설정 요청 다이얼로그 띄우기
- [ ] 코고가 눌러졌을때, 다이얼로그 띄우기
